info:
    description: "TrainingTrackerRest REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "TrainingTrackerRest"
    version: v1.0
openapi: 3.0.1
paths:
    /myusers:
        get:
            tags:
                - MyUsers
            operationId: getAllUsers
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/MyUser'
                        application/xml:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/MyUser'
                '400':
                    description: Invalid status value
components:
    schemas:
        MyUser:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                username:
                    type: string
                firstName:
                    type: string
                lastName:
                    type: string
                email:
                    type: string
                password:
                    type: string
                phone:
                    type: string